name: "commit-push-and-pr"
description: "Create new branch, then commit, push and make PR"
inputs:
  user-name:
    description: "github user name"
    required: true
  email:
    description: "github user's email"
    required: true
  base-branch:
    description: "base branch"
    required: true
    default: master
  comment:
    description: "commit comment"
  branch-name:
    description: "new branch name"
  pr-title:
    description: "pull request title"
  pr-comment:
    description: "pull request comment"
runs:
  using: 'docker'
  image: Dockerfile
  args:
    - ${{ inputs.user-name }}
    - ${{ inputs.email }}
    - ${{ inputs.base-branch }}
    - ${{ inputs.branch-name }}
    - ${{ inputs.comment }}
    - ${{ inputs.pr-title }}
    - ${{ inputs.pr-comment }}