name: "commit-push-and-pr"
description: "Create new branch, then commit, push and make PR"
inputs:
  user-name:
    description: "github user name"
    required: true
  email:
    description: "github user's email"
    required: true
  base-branch:
    description: "base branch"
    required: true
    default: master
  branch-name:
    description: "new branch name"
  comment:
    description: "commit comment"
  pr-title:
    description: "pull request title"
  pr-comment:
    description: "pull request comment"
  github-token:
    description: "GitHub Personal Access Token"
  label:
    description: "Pull request's labels"
  auto-merge:
    description: "set 1 if you want to merge automatically"
runs:
  using: 'docker'
  image: Dockerfile
  args:
    - ${{ inputs.user-name }}
    - ${{ inputs.email }}
    - ${{ inputs.base-branch }}
    - ${{ inputs.branch-name }}
    - ${{ inputs.comment }}
    - ${{ inputs.pr-title }}
    - ${{ inputs.pr-comment }}
    - ${{ inputs.github-token }}
    - ${{ inputs.label }}
    - ${{ inputs.auto-merge }}